# Generated by Django 5.0.3 on 2024-03-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhook_forwarder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookpayload",
            name="http_query_params",
            field=models.JSONField(default=dict),
        ),
    ]
