# Generated by Django 5.0.3 on 2024-03-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IncomingAPICall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                ("source", models.CharField(db_index=True, max_length=64)),
                ("destination", models.CharField(db_index=True, max_length=64)),
                (
                    "call_type",
                    models.CharField(
                        db_index=True, default=None, max_length=64, null=True
                    ),
                ),
                ("url", models.CharField(max_length=1024)),
                ("method", models.CharField(default="GET", max_length=16)),
                ("body", models.TextField(default="")),
                ("error", models.TextField(default="")),
                ("status_code", models.PositiveIntegerField(db_index=True, null=True)),
                (
                    "request_duration",
                    models.DecimalField(decimal_places=3, max_digits=6),
                ),
                ("response", models.TextField(default="")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OutgoingAPICall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                ("source", models.CharField(db_index=True, max_length=64)),
                ("destination", models.CharField(db_index=True, max_length=64)),
                (
                    "call_type",
                    models.CharField(
                        db_index=True, default=None, max_length=64, null=True
                    ),
                ),
                ("url", models.CharField(max_length=1024)),
                ("method", models.CharField(default="GET", max_length=16)),
                ("body", models.TextField(default="")),
                ("error", models.TextField(default="")),
                ("status_code", models.PositiveIntegerField(db_index=True, null=True)),
                (
                    "request_duration",
                    models.DecimalField(decimal_places=3, max_digits=6),
                ),
                ("response", models.TextField(default="")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
